### ISSUE TITLE
Can't compile :(

### ISSUE THREAD

**Issue by lethalrush** [Furkanzmc/ofxFFmpegRecorder#2]
Hi, I'm trying to compile your /example, and I am getting a bunch of errors.  Do you know why? 

![image](https://user-images.githubusercontent.com/16144142/37192377-15e71a1c-2333-11e8-86b1-8226d568c0fc.png)

**Comment by Furkanzmc** [comment]
This is a way too late answer. But I don't use openFrameworks anymore so I had never checked this. For people who end up getting the same error, please see the fork from [NickHardeman](https://github.com/NickHardeman/ofxFFmpegRecorder). Specifically, [this commit](https://github.com/NickHardeman/ofxFFmpegRecorder/commit/c431afc96a12e8ce195a07c1e79496302521eb0c).
